services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      FOREBYGGINGSPLAN_API_BASEURL: http://backend:4000
    ports:
      - 3000:3000

  backend:
    image: ghcr.io/navikt/forebyggingsplan:latest
    environment:
      SERVER_PORT: "4000"
    ports:
      - 4000:4000