FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./
COPY next.config.js .
COPY next-env.d.ts .
COPY tsconfig.json .
COPY src ./src
COPY .npmrc ./
COPY stubs ./stubs

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm install
RUN npm run build

EXPOSE 3000

RUN chown -R node:node ./.next

USER node

CMD npm run start
