services:
  backend:
    image: ghcr.io/navikt/forebyggingsplan:latest
    environment:
      SERVER_PORT: "4000"
    ports:
      - 4000:4000

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      FOREBYGGINGSPLAN_API_BASEURL: http://backend:4000
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
