services:
  altinn:
    container_name: altinn
    image: wiremock/wiremock
    ports:
      - 9090:8080
    volumes:
      - ./stubs:/home/wiremock

  database:
    container_name: database
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

  backend:
    container_name: backend
    depends_on:
      - wonderwall
      - database
    image: ghcr.io/navikt/forebyggingsplan:latest
    pull_policy: always
    environment:
      SERVER_PORT: "8081"
      TOKEN_X_CLIENT_ID: "forebyggingsplan"
      TOKEN_X_ISSUER: "http://host.docker.internal:8080/tokenx"
      TOKEN_X_JWKS_URI: "http://host.docker.internal:8080/tokenx/jwks"
      TOKEN_X_TOKEN_ENDPOINT: "http://host.docker.internal:8080/tokenx/token"
      TOKEN_X_PRIVATE_JWK: >
        {
              "p": "1sKc9CQFXJ5q14wGjk6bAhIaWBiM2ZJHNCLcME0P60q_dNaC7osoj0-zDTwUWdiREIiI2y3DAArAGNlhyZqZwDNumL08_pM-ePXVoqiZWZ87Ch8g8csx27yU_AsDj6h64qRpV07x_TOzXRJdP5iQm_IO3qjyul9qlnXyd2X9h3c",
              "kty": "RSA",
              "q": "xkS_rKKUfowRYmHfha4birMJMvrRZEBmvOPs9gerRUyIy32R36UT5f2B8xwycExivtZpnlz-YgBrglIpWWXX1gUtgLb4dV_YQNE4rABQjWoa62NJeCeaL5mOoVJ-6Xx2mgt9Tb9JdZVyfQuC9-s74ImgKyYaN8y7LcW7EqxNa60",
              "d": "TUr875CxdUBnuufXfGe9WELPlLE2N4tVtHO85qrVuwn41CueKKk92bF6mK4fFF_oIP6Ja22B96i7d-AY5GtLcwIJA_HNy6ndYJCWiMX9GlDJ7Y2TyYXrk4YXpZQWI3x18X7wbDs0JX1eVsxs2VWhjzyEsJfEbp0cyagBIZR_GE_WecEahhBUV2eGl9qf0qL50MnckFOZhQErEpyr0XPTfjqktwpmjZkTdONyvKoJhXhm7bngFQHl63RX3fIElsYFsvMYNpAH_I5NZg76Va79txrfR7X0diG6XZ4Kc5iUXXL1ZFnqgijVOzUYfldDikxaXc5wKPL5Jbs2GBe1fB14eQ",
              "e": "AQAB",
              "use": "sig",
              "kid": "tokenx",
              "qi": "zNeG8JxnjxSlCWbRv2sHwld6tf1OtDKTimo4VbNdOqmrm8sSUkuM9h0mrH0ZUbC7Q1n0Cp-4T_Q82QVzKXX71bGSolTI7c6NCTnzQXgTEylMaHgv-9MIG1N4raxWemlOt_0ZgdTjwDWNPXfbbx0oyc4NBJVZpQH_KEXKirAY5aI",
              "dp": "Pbe8B2V6rP1R0xQIpkjsvxGYxIx5neUt1UvXX4Il-waGMvuasRcI1vaejEUhzBgyyD-UpPhnu9FbF0kRkzB80wF03Sw1JSwHnhd4B8DQITNjcisz-ojckTuGzVAU--n9NrjtFQw4-v0qpKqsZaRgmpBbuZ1v9COLrCXFQo7q500",
              "alg": "RS256",
              "dq": "Ccu_xKHLwGzfNwMq7gnqJnIuFCy8R72-1bpVLNq4JZZgc91iZbBcSVK7Ju3PuCiuAEvLsB1cHC91IF062cXkYhijZOalY_c2Ug2ERUtGr5X8eoDPUnZyccOefm37A0I5Aedra3n2AS8_FtqIwAMJVFC4bylUxkkBPoO0eHm24Yk",
              "n": "plQx4or1C_Xany-wjM7mPHB4CAJPk3oOEdDSKpTwJ2dzGji5tEq7dUxExyhFN8f0PUjBjXyPph0gmDWaJG64fnhSSwVI-8Tdf2PppuK4rdCtWSPLgZ_DJ2DruxHgeXgwvJnX1HRfqhJF2p4ClkRUiVXZKFOhRPMGVgg18fnV9fXz5C4JacP_fmh498ktEohwcL3Pbv5DI_po_i0OiyF_M-9Iic3Ss80j22hs1wsNBGEMHvofWs7sl3ufwxmUCIstnDNSat840-n21Q4GV2v4L2kpROUw6l4ZmqZxoGl7eRSDS_VC5rPQoQEZYfyCiq6o1W5p9UXnoQin1zn0lr5Iaw"
        }
      ALTINN_RETTIGHETER_PROXY_CLIENT_ID: hei
      TZ: "Europe/Oslo"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: test
      DB_DATABASE: postgres
      ALTINN_RETTIGHETER_PROXY_URL: "http://altinn:8080/altinn"
    ports:
      - 8081:8081
      - 5005:5005

  wonderwall:
    image: "ghcr.io/nais/wonderwall:latest"
    container_name: wonderwall
    network_mode: host
    depends_on:
      - auth
    restart: on-failure
    environment:
      WONDERWALL_OPENID_CLIENT_ID: "forebyggingsplan"
      WONDERWALL_OPENID_CLIENT_JWK: "{\"p\":\"4_8iPMp54U-RtJ000k7ikqRFSc1DmnH3EnDtWR3kumNSlsRUHuF_VLATOf9_gkOtwXBy9CjVVJbfM6hhJZYME231jIZxKWTx8rfQ5RYFdRkJeDqVyz1SmJt8eBW8WENN3CFZ3J1Sel6BWfhuC6uj30J0TqaSIGH2vilTMFNeHr8\",\"kty\":\"RSA\",\"q\":\"x36QcU_-qV_Idl2CMhSmhkvRaMR04C50Pj5-2FxuVPyzKoL-1JI8_bOeXPv487OUkVt85lLI-nbWcjUFC2rVl6hHZJgltbvzOzob3LoBDG3WF4ChreOwjQnu1uAnbB0iBaG2ss9beoGW6P4U8IroQBlsjRt9mBrHoYOsls9PGlc\",\"d\":\"eseC8V_8MSvlq7xU96hVopmn_r5-sq5Mbo-CigQK8LQoFoMDI33t8qic-ToKkHoF3XtewSeGBYATAFvfiQemcLWwqFuRq-sBLVAH4AQFPkxQxuRl1QrrvglAVxjCtmJZoHH2NNlJXzmwe0aNH5dBsm0jRVQNU9SLFfCwghPm3vpjYFX4uL3h_4_XT3hTMowLGARe9HOErIl52TAIfPV0riuaMkKZLqnsKoPO_uL9FyxBY97DcIPD45LL1nqBNkZWiz7XhZWU9rWS2EBGXdP3dZ-JdvmTdTvGtFceJgbtPNHnIvMSVqEadJq9WmP4WIDoppo6xLL9h6JoQ7faI_U39Q\",\"e\":\"AQAB\",\"use\":\"sig\",\"kid\":\"forebyggingsplan\",\"qi\":\"D93yW3TJFoqlDomyKkUv1G-xmdlCZSVpKT0U3tTrLCeiK8XJRvJRKWR0imwWpyx4l8_N_XkcIYtGqyHD0DsebTW1MNU51xsCTOmwAoHYvkuO_DKk0T0M1qN5f1Tjr0W8DzdwBYG5m-KovDz7ZC-3QKw8kAz0PgQSCqg4DkjhlAc\",\"dp\":\"ssRHWhcAPZOgEVf6JLRJnuVClr1lNmIJceItl-SChUp_ZUuHEbeJmSN9z8nvdnoOcU_0MlEaA_tQAzcRBOGDknBzSb3YWLaXptJN7nG30brR2_1Dmln4u0Oe8qFIToRnNiTIStzn4J7dGWhbELeCA_odK9YbWVy2lR_d5FRZxg0\",\"alg\":\"RS256\",\"dq\":\"xw2SMn4PLBFWhERpVG8meXnNSSw9MjMn6bOR_XC85i_-1bw_aPtBwCMpML56eTAGXcNbrLWNs9w_vVUJ44qF9P0Dv2vQtLUEzWP9yRAPW8d8h5bhvBAkaZYvqlee_lFTUSs6kNA2BtanLXPYkOsJMmwr0-BKQSr3ZkFsRE42L6E\",\"n\":\"sawL1IlvPmkkk2h99lGejgASOehqDJaaPchOPYx0ibbqoZ_-lvbJ7M6WsnJT-k42DBebRhxQlszdJ3z-u7fBx0KUB7vouyZQUzaA2GctmelrGFdNehJl4Fb-1PY22_K6UFIoi4DC8wWiS__Me65FWBmsHkV8PM9O4nPhbIDzwX777P5kIz9Bx8mV1m3MHGYrBVP7k7f6BPCjpuoxeN2jB6PmRLM3j8R0dze0uAYXhfpAHwZxZD2ORiSpUIE29cQXy4kgSX45SIL4CnxqWFVyKpybaCQPGL5vEXqKDbACAtYuoXMuvD9xfCh7-FKDRePRTiLgiLnR0HyCXFq10gzY6Q\"}"
      WONDERWALL_OPENID_WELL_KNOWN_URL: http://host.docker.internal:8080/idporten/.well-known/openid-configuration
      WONDERWALL_INGRESS: http://localhost:4000
      WONDERWALL_BIND_ADDRESS: 0.0.0.0:4000
      WONDERWALL_UPSTREAM_HOST: host.docker.internal:3000
      WONDERWALL_AUTO_LOGIN: "true"
      WONDERWALL_LOG_FORMAT: "text"

  auth:
    image: "ghcr.io/navikt/mock-oauth2-server:0.5.4"
    container_name: auth
    ports:
      - "8080:8080"
    environment:
      JSON_CONFIG: >
        {
            "interactiveLogin": false,
            "httpServer": "NettyWrapper",
            "tokenCallbacks": [
                {
                    "issuerId": "idporten",
                    "tokenExpiry": 3600,
                    "requestMappings": [
                        {
                            "requestParam": "grant_type",
                            "match": "*",
                            "claims": {
                                "sub": "12345678901",
                                "pid": "12345678901",
                                "acr": "Level4"
                            }
                        }
                    ]
                }
            ]
        }

  frontend:
    container_name: frontend
    restart: always
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      FOREBYGGINGSPLAN_API_BASEURL: http://backend:8081
      FOREBYGGINGSPLAN_CLIENT_ID: forebyggingsplan
      IDPORTEN_WELL_KNOWN_URL: http://host.docker.internal:8080/idporten/.well-known/openid-configuration
      NAIS_CLUSTER_NAME: "localhost"
      TOKEN_X_CLIENT_ID: "localhost:pia:forebyggingsplan-frontend"
      TOKEN_X_ISSUER: http://host.docker.internal:8080/tokenx
      TOKEN_X_TOKEN_ENDPOINT: http://host.docker.internal:8080/tokenx/token
      TOKEN_X_WELL_KNOWN_URL: http://host.docker.internal:8080/tokenx/.well-known/openid-configuration
      TOKEN_X_PRIVATE_JWK: "{\"p\":\"zoo6Mgk8VMKI461_dzeU-wflmGVs1jcl4dxe8_W-9jeR84YISN13Uk3TU2kqLGz07Z8eMRkOnMkq2abGfQAwxyG3PPVM0xPr8tg8NVpClMvJFRd9RlVJ485IMmJ0t8t3sjiZo6q_ndqYJ5G6VMi3_o7s8gACKnnoh7ohTB49ep0\",\"kty\":\"RSA\",\"q\":\"wMAmevT8vJaD58QeytnbW9TWwqxPFJzu9YPjgXkbPA234HKF4UXZnIeqMtrBb3Ea3-vxVtuxGPT7wULfgCd7WJMh625tX7_WxkHSJTy_TY4-HETBIcZrikdJ8vPQcemvpCyla6DvUpwiQBc0G-9wBov1_938Jk0uOMy-3Bq6zJE\",\"d\":\"X56QX4_vtuCntzj4X7utYNMn9qHjz6B2tl9V4_UMPUjpIUJiNXQlA9CHsxeP4VzOUeerKL9EFmMoYjDYj_uOfLsJwQP-eRrlJg0da4dF2HTVXUb6qJOOGXq86GQ8L7KD2_gSo4uHydpTqLe1r9yhabw8Dcbsm4YKJ7MNle3aoovDShlwCgul5V0_JYD0bvOHMSFI4aomIUk3w5dp0g8fecNYsRCOaaZpjt9yHrz9Ryd1lbx24eu8UmJi7WH4SIJFWaKxKqYEoaC832-3A7TCycayFe517akNU1_nq8TDvgDDjjCEm2T8FOqed1tjdc0wJVQu_w9qU2ZUTuGPMmYtwQ\",\"e\":\"AQAB\",\"use\":\"sig\",\"kid\":\"localhost:pia:forebyggingsplan-frontend\",\"qi\":\"XmjNimJ9zdB4s0kicusSS5UcaL2p1uQYtMrNO8YH75RmUIh092iUhlF_rJ7SiexZ4m-th3I_fuLhchECysV-T4l9H4pxRjrrHnlF1X0NkMcohw8J1gx_Od8wubJQYSJ3S8xDGZEDCBIuCBslPwOtJrrf2t5eJS9dNzgPT1UC4Lg\",\"dp\":\"Dru3iQg1oIo7_5nJxPRXEU0v6J4blHBcqG7y6w41sBSoualu_9ukfl-E2qde1cpz8ltuaOwzqaWEBACsmhAgaqQSESwibdA2_ZzFNr0YkMq0rmd9jT3aRoDZj5aMYuwFvtXgx9cPUjBcuD3h_9hNn8AMUPsFLIiDuOLjKy3hDtU\",\"alg\":\"RS256\",\"dq\":\"oxSwOg33nDQZDEnx550lrG_K-NDC4-TXhSB-p7fopAnTTnJ29Z-cu4RJK1fMm9Ztb5F4Ew4zq7LzIpPK9-nvwYRTCZfXsFBmjj14aIsaLKsxv8coRMRVjpw8Y_OHpCmcsuIXX5W9hv6VN_ap3wzZkqBulXqi8WERv3rz7NQswhE\",\"n\":\"m4KyXOSe_bjAG9rsHR8nrTabipYIAGIGvUOJ4jlRBQ7MYmO5LXgt8YM9ctKdfhbHe78oNa8iPvOmDXAMtf8jlYLGrcLRqb_9kQfKo-uNeC5JG-xBR2NbMFGPYlr9KOxMC-ReehO6R7YjjpxVQJQa83awR0WzCC4h2KIBXaF8dfsNqqCsz9hj2IU6gj6DoPSTClokHFFsao6HtDagQqykxFmn4ogZxj1eF8aZ3W5LBBAMi6ObVapLzCGrw-l0LaQk0ELRGPSouIQEd21mw7rX99xi9fq5BMZd18DBwRolEY8NDUD1PFuUm4p4CY6ZsKHhLTxORugbxlzKR6BBJpmO7Q\"}"
    ports:
      - 3000:3000
