ingresses:
- "https://forebyggingsplan-frontend.dev.nav.no/forebyggingsplan"
forebyggingsplanClientId: "dev-gcp:pia:forebyggingsplan"
sykefravarstatistikkApiClientId: "dev-fss:arbeidsgiver:sykefravarsstatistikk-api"
sykefravarstatistikkApiBaseurl: "https://sykefravarsstatistikk-api.dev-fss-pub.nais.io/sykefravarsstatistikk-api"
dekoratorEnv: "dev"
