navn: "forebyggingsplan-frontend"
ingresses:
- "https://forebyggingsplan-frontend.dev.nav.no/forebyggingsplan"
forebyggingsplanClientId: "dev-gcp:teamia:forebyggingsplan"
sykefravarstatistikkApiClientId: "dev-fss:arbeidsgiver:sykefravarsstatistikk-api"
sykefravarstatistikkApiBaseurl: "https://sykefravarsstatistikk-api.dev-fss-pub.nais.io/sykefravarsstatistikk-api"
iaMetrikkerApiClientId: "dev-gcp:arbeidsgiver:ia-tjenester-metrikker"
iaMetrikkerApiBaseurl: "https://ia-tjenester-metrikker.dev.nav.no/ia-tjenester-metrikker"
forebyggingsplanBaseurl: "http://forebyggingsplan.teamia.svc.cluster.local"
dekoratorEnv: "dev"
minReplicas: 2
maxReplicas: 4
autoLoginEnabled: true
