apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{navn}}
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: {{autoLoginEnabled}}
  port: 3000
  liveness:
    path: "/forebyggingsplan/api/isAlive"
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/forebyggingsplan/api/isReady"
    port: 3000
    initialDelay: 20
    timeout: 60
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: api.sanity.io
        - host: 2u7e6oll.api.sanity.io
        - host: apicdn.sanity.io
        - host: 2u7e6oll.apicdn.sanity.io
        - host: cdn.sanity.io
        - host: {{ sykefravarstatistikkApiHost }}
      rules:
        - application: forebyggingsplan
          namespace: teamia
  env:
    - name: FOREBYGGINGSPLAN_API_BASEURL
      value: {{ forebyggingsplanBaseurl }}
    - name: FOREBYGGINGSPLAN_CLIENT_ID
      value: {{ forebyggingsplanClientId }}
    - name: SYKEFRAVARSSTATISTIKK_API_CLIENT_ID
      value: {{ sykefravarstatistikkApiClientId }}
    - name: SYKEFRAVARSSTATISTIKK_API_BASEURL
      value: {{ sykefravarstatistikkApiBaseurl }}
    - name: IA_METRIKKER_API_CLIENT_ID
      value: {{ iaMetrikkerApiClientId }}
    - name: IA_METRIKKER_API_BASEURL
      value: {{ iaMetrikkerApiBaseurl }}
    - name: DECORATOR_ENV
      value: {{ dekoratorEnv }}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
