apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "forebyggingsplan-frontend"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  port: 3000
  liveness:
    path: "/forebyggingsplan/api/isAlive"
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/forebyggingsplan/api/isReady"
    port: 3000
    initialDelay: 20
    timeout: 60
  accessPolicy:
    outbound:
      rules:
        - application: forebyggingsplan
  env:
    - name: FOREBYGGINGSPLAN_API_BASEURL
      value: {{ forebyggingsplanBaseurl }}
    - name: FOREBYGGINGSPLAN_CLIENT_ID
      value: {{ forebyggingsplanClientId }}
    - name: SYKEFRAVARSSTATISTIKK_API_CLIENT_ID
      value: {{ sykefravarstatistikkApiClientId }}
    - name: SYKEFRAVARSSTATISTIKK_API_BASEURL
      value: {{ sykefravarstatistikkApiBaseurl }}
    - name: DECORATOR_ENV
      value: {{ dekoratorEnv }}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
