navn: "forebyggingsplan-frontend"
ingresses:
- "https://arbeidsgiver.nav.no/forebyggingsplan"
forebyggingsplanClientId: "prod-gcp:teamia:forebyggingsplan"
sykefravarstatistikkApiClientId: "prod-fss:arbeidsgiver:sykefravarsstatistikk-api"
sykefravarstatistikkApiHost: "sykefravarsstatistikk-api.prod-fss-pub.nais.io"
sykefravarstatistikkApiBaseurl: "https://sykefravarsstatistikk-api.prod-fss-pub.nais.io/sykefravarsstatistikk-api"
iaMetrikkerApiClientId: "prod-gcp:arbeidsgiver:ia-tjenester-metrikker"
iaMetrikkerApiHost: "arbeidsgiver.nav.no"
iaMetrikkerApiBaseurl: "http://ia-tjenester-metrikker.arbeidsgiver.svc.cluster.local/ia-tjenester-metrikker"
forebyggingsplanBaseurl: "http://forebyggingsplan.teamia.svc.cluster.local"
grafanaAgentCollectorUrl: "https://telemetry.nav.no/collect"
dekoratorEnv: "prod"
minReplicas: 2
maxReplicas: 4
autoLoginEnabled: true
