navn: "forebyggingsplan-frontend"
ingresses:
- "https://arbeidsgiver.nav.no/forebyggingsplan"
forebyggingsplanClientId: "prod-gcp:pia:forebyggingsplan"
sykefravarstatistikkApiClientId: "prod-fss:arbeidsgiver:sykefravarsstatistikk-api"
sykefravarstatistikkApiBaseurl: "https://sykefravarsstatistikk-api.prod-fss-pub.nais.io/sykefravarsstatistikk-api"
iaMetrikkerApiClientId: "prod-gcp:arbeidsgiver:ia-tjenester-metrikker"
iaMetrikkerApiBaseurl: "https://arbeidsgiver.nav.no/ia-tjenester-metrikker"
forebyggingsplanBaseurl: "http://forebyggingsplan"
dekoratorEnv: "prod"
minReplicas: 2
maxReplicas: 4
