name: Build and deploy forebyggingsplan-frontend
on:
  push:
    branches:
      - main
      - redirect-fra-labs-til-dev-ekstern

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    name: Bygg og test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Legg til host.docker.internal i /etc/hosts
        run: sudo echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: 'https://npm.pkg.github.com'

      - name: Installer dependencies
        run: npm ci

      - name: Kjør tester
        run: npm run test:ci

      - name: Bygg prosjekt
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image and push to ghcr
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,${{ env.IMAGE }}
          context: .
          secrets: |
            "NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}"

  deploy:
    strategy:
      matrix:
        cluster: [ dev, prod ]
    name: Deploy app to ${{ matrix.cluster }}
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/${{ matrix.cluster }}.yaml

  deploy-feature-branch-to-dev:
    strategy:
      matrix:
        cluster: [ dev ]
    name: Deploy app to dev (feature branch)
    needs: build
    if: github.ref == 'refs/heads/redirect-fra-labs-til-dev-ekstern'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to dev-ekstern
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/${{ matrix.cluster }}.yaml

  deploy-main-or-feature-branch-to-dev-ekstern:
    strategy:
      matrix:
        cluster: [ dev ]
    name: Deploy app to dev-ekstern
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/redirect-fra-labs-til-dev-ekstern'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to dev-ekstern
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/dev-ekstern.yaml

  deploy-main-or-feature-branch-to-labs:
    strategy:
      matrix:
        cluster: [ labs ]
    name: Deploy app to labs
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/redirect-fra-labs-til-dev-ekstern'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to labs
        uses: nais/deploy/actions/deploy@v1
        env:
          DEPLOY_SERVER: deploy.nais.io:443
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/${{ matrix.cluster }}.yaml
