name: Build and deploy lydia-radgiver-frontend
on:
  push:
    branches:
      - main
env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    name: Bygg og test
    runs-on: ubuntu-latest
    steps:
      - name: Legg til host.docker.internal i /etc/hosts
        run: sudo echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup containers
        run: docker-compose -f docker-compose-e2e.yaml up -d

      - name: Sleep a bit
        run: sleep 5s

      - name: Echo docker status
        run: docker ps

      - name: Check hostnames
        run: netstat -lt

      - name: Do curl
        run: docker run --network container:backend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8081/internal/isAlive

      - name: cypress
        uses: cypress-io/github-action@v4
        env:
          DEBUG: 'cypress:*'

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

      - name: Teardown containers
        if: always()
        run: docker-compose down

      - name: Build docker image and push to ghcr
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,${{ env.IMAGE }}
          context: .
  deployAppToDev:
    name: Deploy app to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/dev.yaml
