name: Buld and deploy sanity prod
on:
  push:
    branches:
      - main
    paths:
      - sanity-studio/**
      - .github/workflows/sanity_prod.yaml

jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity
    steps:
      - uses: actions/checkout@v2
      - run: cd sanity-studio
      - uses: sanity-io/github-action-sanity@v0.4-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
        with:
          args: deploy
