name: Build and deploy sanity studio
on:
  push:
    branches:
      - main
    paths:
      - sanity-studio/**
      - .github/workflows/sanity_prod.yaml

jobs:
  sanity-deploy:
    defaults:
      run:
        working-directory: sanity-studio
    runs-on: ubuntu-latest
    name: Deploy Sanity
    env:
      SANITY_STUDIO_PROJECT_ID: 2u7e6oll
      SANITY_STUDIO_DATASET: production
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Install deps
        run: npm install
      - name: Setup sanity cli
        run: npm install -g @sanity/cli
      - name: Deploy sanity
        run: sanity deploy